routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ClientPersonController@index');
Route::resource('/client', 'ClientPersonController');

app/Person.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Person extends Model
{
    protected $fillable = ['name', 'ssn', 'address', 'gender', 'birthday'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ApiPersonController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StorePerson;
use App\Http\Requests\UpdatePerson;
use App\Http\Resources\PersonResource;
use App\Person;
use Repositories\PersonRepository as ICrud;
use Symfony\Component\HttpFoundation\Response;

class ApiPersonController extends Controller
{
    protected $persons; //Repository

    public function __construct(ICrud $p)
    {
        $this->persons = $p;
    }


    /**
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Illuminate\Http\Resources\Json\AnonymousResourceCollection|Response
     */
    public function index()
    {
        try {
            return json_encode($this->persons->all());
        } catch (\Exception $e) {

            return response(null, Response::HTTP_INTERNAL_SERVER_ERROR);

        }

    }

    /**
     * @param StorePerson $request
     * @return \Illuminate\Contracts\Routing\ResponseFactory|Response
     */
    public function store(StorePerson $request)
    {
        try {

            $return = $this->persons->store($request);
            if (isset($return)) {
                return response(['data' => $return], Response::HTTP_CREATED);
            } else {
                return response(null, Response::HTTP_BAD_REQUEST);
            }
        } catch (\Exception $e) {
            return response(null, Response::HTTP_INTERNAL_SERVER_ERROR);

        }


    }

    /**
     * @param Person $person
     * @return PersonResource
     */
    public function show(Person $person)
    {
        try {
            return json_encode($this->persons->show($person));
        } catch (\Exception $e) {
            return response(null, Response::HTTP_INTERNAL_SERVER_ERROR);

        }


    }

    /**
     * @param UpdatePerson $request
     * @param Person $person
     * @return \Illuminate\Contracts\Routing\ResponseFactory|Response
     */
    public function update(UpdatePerson $request, Person $person)
    {
        try {
            $return = $this->persons->update($request, $person);
            if (isset($return)) {
                return response(['data' => $return], Response::HTTP_CREATED);
            } else {
                return response(null, Response::HTTP_BAD_REQUEST);
            }
        } catch (\Exception $e) {
            return response(null, Response::HTTP_INTERNAL_SERVER_ERROR);
        }


    }

    public function find($id)
    {
        try {
            $person = $this->persons->find($id);


            if (!isset($person)) {
                return response(null, Response::HTTP_NOT_FOUND);
            } else {
                return json_encode($person);
            }

        } catch (\Exception $e) {
            return response(null, Response::HTTP_INTERNAL_SERVER_ERROR);
        }

    }

    public function destroy(Person $person)
    {
        try {
            $this->persons->destroy($person);
            return response(null, Response::HTTP_NO_CONTENT);
        } catch (\Exception $e) {
            return response(null, Response::HTTP_INTERNAL_SERVER_ERROR);
        }

    }
}

app/Http/Controllers/ClientPersonController.php
<?php

namespace App\Http\Controllers;


use Carbon\Carbon;
use GuzzleHttp\Client;
use GuzzleHttp\Exception\ClientException;
use Illuminate\Http\Request;

class ClientPersonController extends Controller
{
    public function index()
    {
        try {
            $client = new Client();
            $res = $client->get(route('persons.index'));
            $persons = json_decode($res->getBody()->getContents());
            $men = 0;
            $women = 0;
            $ages = [
                0 => 0, //0 a 9
                1 => 0, //10 a 19
                2 => 0, //20 a 29
                3 => 0, //30 a 39
                4 => 0  //Maior que 40
            ];
            foreach ($persons as $person) {
                if ($person->genero == 'Masculino') {
                    $men++;
                } else {
                    $women++;
                }
                $age = Carbon::parse($person->nascimento)->age;
                if ($age >= 0 && $age <= 9) {
                    $ages[0]++;
                } else if ($age >= 10 && $age <= 19) {
                    $ages[1]++;
                } else if ($age >= 20 && $age <= 29) {
                    $ages[2]++;
                } else if ($age >= 30 && $age <= 39) {
                    $ages[3]++;
                } else {
                    $ages[4]++;
                }

            }

            return view('persons.index', ['persons' => $persons, 'men' => $men, 'women' => $women, 'ages' => $ages]);
        } catch (\Exception $e) {
            return redirect()->action('ClientPersonController@index')->with('msg', 'Não foi possivel executar a ação');
        }

    }


    public function create()
    {
        return redirect()->action('ClientPersonController@index');
    }

    public function store(Request $r)
    {
        try {
            unset($r['_method']);
            unset($r['_token']);
            $endpoint = url('/') . '/api/persons';
            $options = [
                'headers' => ['Content-Type' => 'application/json',
                    'Accept' => 'application/json'],
                'json' => ['nome' => $r->nome,
                    'cpf' => $r->cpf,
                    'endereco' => $r->endereco,
                    'genero' => $r->genero,
                    'id' => $r->id,
                    'nascimento' => $r->nascimento],

            ];

            $client = new Client();
            $client->post($endpoint, $options);
            return redirect()->action('ClientPersonController@index');
        } catch (\Exception $e) {
            return redirect()->action('ClientPersonController@index')->with('msg', 'Não foi possivel executar a ação');
        }

    }


    public function edit(Request $r)
    {
        return redirect()->action('ClientPersonController@index');

    }

    public function update(Request $r)
    {
        try {

            unset($r['_method']);
            unset($r['_token']);
            $endpoint = url('/') . '/api/persons/' . $r->id;
            $options = [
                'headers' => ['Content-Type' => 'application/json',
                    'Accept' => 'application/json'],
                'json' => ['nome' => $r->nome,
                    'cpf' => $r->cpf,
                    'endereco' => $r->endereco,
                    'genero' => $r->genero,
                    'id' => $r->id,
                    'nascimento' => $r->nascimento],

            ];

            $client = new Client();
            $client->put($endpoint, $options);

            return redirect()->action('ClientPersonController@index');
        } catch (ClientException $e) {

            return redirect()->action('ClientPersonController@index')->with('msg', 'Não foi possivel executar a ação');
        }

    }

    public function destroy(Request $r)
    {
        try {
            $client = new Client();
            $client->delete($r->href);

            return redirect()->action('ClientPersonController@index');
        } catch (\Exception $e) {
            return redirect()->action('ClientPersonController@index')->with('msg', 'Não foi possivel executar a ação');
        }


    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/layouts/sbadmin2.blade.php
<!DOCTYPE html>
<html lang="en">
@include('partials._head')

<body>
<div id="wrapper">
    @include('partials._navbar')
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Dashboard</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="content-wrapper">
            <div class="container-fluid">
                @yield('content')
            </div>
        </div>
    </div>
    <!-- /#page-wrapper -->
</div>
<!-- /#wrapper -->

@include('partials._bodyScripts')

</body>

</html>

resources/views/partials/_bodyScripts.blade.php
<!-- jQuery -->
<script src="{{asset('startbootstrap-sb-admin-2/vendor/jquery/jquery.min.js')}}"></script>


<!-- Bootstrap Core JavaScript -->
<script src="{{asset('startbootstrap-sb-admin-2/vendor/bootstrap/js/bootstrap.min.js')}}"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="{{asset('startbootstrap-sb-admin-2/vendor/metisMenu/metisMenu.min.js')}}"></script>

<!-- Morris Charts JavaScript -->
{{--<script src="{{asset('startbootstrap-sb-admin-2/vendor/raphael/raphael.min.js')}}"></script>--}}
{{--
<script src="{{asset('startbootstrap-sb-admin-2/vendor/morrisjs/morris.min.js')}}"></script>
<script src="{{asset('startbootstrap-sb-admin-2/data/morris-data.js')}}"></script>
--}}

<!-- Custom Theme JavaScript -->
<script src="{{asset('startbootstrap-sb-admin-2/dist/js/sb-admin-2.js')}}"></script>

resources/views/partials/_chartsJs.blade.php
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>

resources/views/partials/_dashboardCardNewPersonModal.blade.php
<div id="myModalPerson" class="modal fade" role="dialog">
    <div class="modal-dialog modal-sm">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Nova Pessoa</h4>
            </div>
            <div class="modal-body">
                @include('partials._dashboardNewPersonForm')
            </div>
        </div>

    </div>
</div>

resources/views/partials/_dashboardCards.blade.php
<div class=" col-md-4">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-3">
                    <i class="fa fa-comments fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                    <div class="huge">{{count($persons)}}</div>
                    <div>Pessoas</div>
                </div>
            </div>
        </div>
        <a href="#" data-toggle="modal" data-target="#myModalPerson">
            <div class="panel-footer">
                <span class="pull-left">Nova Pessoa</span>
                <span class="pull-right"><i class="fa fa-plus-circle"></i></span>
                <div class="clearfix"></div>
            </div>
        </a>
    </div>

</div>
<div class="col-md-4">
    <div class="panel panel-green">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-3">
                    <i class="fa fa-tasks fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                    <div class="huge">{{$men}}</div>
                    <div>Homens</div>
                </div>
            </div>
        </div>

    </div>
</div>
<div class="col-md-4">
    <div class="panel panel-red">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-3">
                    <i class="fa fa-tasks fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                    <div class="huge">{{$women}}</div>
                    <div>Mulheres</div>
                </div>
            </div>
        </div>

    </div>
</div>

{{--
<div class="col-lg-3 col-md-6">
    <div class="panel panel-yellow">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-3">
                    <i class="fa fa-tasks fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                    <div class="huge">{{$undefined}}</div>
                    <div>Indefinidos</div>
                </div>
            </div>
        </div>

    </div>
</div>--}}

resources/views/partials/_dashboardDonutChart.blade.php
@include('partials._chartsJs')
<div class="well well-sm">
    <canvas id="personsByAge" ></canvas>
</div>

<script>
    personsByAge();

    function personsByAge() {

        var ages = {!! json_encode($ages) !!};


        var labels = ["0 a 9", "10 a 19", "20 a 29", "30 a 39", "Maior que 40"];
        var data = [];

        for (var i = 0; i < ages.length; i++) {
            data.push(ages[i]);
        }


        var ctx = document.getElementById("personsByAge").getContext('2d');

        var myChart = new Chart(ctx, {
            type: 'doughnut',
            data: {
                labels: labels,
                datasets: [{
                    label: 'Idades',
                    data: data,
                    backgroundColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(255, 0, 0,1)'
                    ],
                    borderColor: [
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                title: {
                    display: true,
                    text: 'Demonstrativo de idades'
                },
                responsive: true,

            }
        });
    }
</script>

resources/views/partials/_dashboardJs.blade.php
<script>
    //bad performance since I already have all the data on the view
    /*function getPersonAjax(href) {

        var xhr = new XMLHttpRequest();
        xhr.open('GET', href);
        xhr.onload = function () {
            if (xhr.status === 200) {
                person = JSON.parse(xhr.responseText)

                var personIdElement = document.getElementById('person-id-show');
                var personNameElement = document.getElementById('person-name-show');
                var personSsnElement = document.getElementById('person-ssn-show');
                var personGenderElement = document.getElementById('person-gender-show');
                var personBirthdayElement = document.getElementById('person-birthday-show');
                var personAddressElement = document.getElementById('person-address-show')

                personIdElement.innerHTML = person.id;
                personNameElement.innerHTML = person.nome;
                personSsnElement.innerHTML = person.cpf;
                personGenderElement.innerHTML = person.genero;
                personBirthdayElement.innerHTML = person.nascimento;
                personAddressElement.innerHTML = person.endereco;
            }
            else {
                alert('Request failed.  Returned status of ' + xhr.status);
            }
        };
        xhr.send();

    }*/

    function destroyPerson(personId) {
        var persons ={!! json_encode($persons) !!};
        var person = null;

        for (var i = 0; i < persons.length; i++) {
            if (persons[i].id === personId) {
                person = persons[i];
                break;
            }
        }


        document.getElementById("person-id-delete").innerHTML = "<strong>Id: </strong>" + person.id;
        document.getElementById("person-name-delete").innerHTML = "<strong>Nome: </strong>" + person.nome;
        document.getElementById("person-ssn-delete").innerHTML = "<strong>CPF: </strong>" + person.cpf;
        document.getElementById("person-gender-delete").innerHTML = "<strong>Gênero: </strong>" + person.genero;
        document.getElementById("person-birthday-delete").innerHTML = "<strong>Nascimento: </strong>" + person.nascimento;
        document.getElementById("person-address-delete").innerHTML = "<strong>Endereço: </strong>" + person.endereco;


        document.getElementById("modalForm").action = '{!! url('/').'/' !!}' + 'client/' + person.id;
        document.getElementById("hrefInputHidden").value = person.href;
    }

    function getPerson(personId) {
        var persons ={!! json_encode($persons) !!};
        var person = null;

        for (var i = 0; i < persons.length; i++) {
            if (persons[i].id === personId) {
                person = persons[i];
                break;
            }
        }
        document.getElementById('person-name-show').innerHTML = "<strong>Id: </strong>" + person.id;
        document.getElementById('person-name-show').innerHTML = "<strong>Nome: </strong>" + person.nome;
        document.getElementById('person-ssn-show').innerHTML = "<strong>CPF: </strong>" + person.cpf;
        document.getElementById('person-gender-show').innerHTML = "<strong>Gênero: </strong>" + person.genero;
        document.getElementById('person-birthday-show').innerHTML = "<strong>Nascimento: </strong>" + person.nascimento;
        document.getElementById('person-address-show').innerHTML = "<strong>Endereço: </strong>" + person.endereco;


    }

    function editPerson(personId) {
        var persons ={!! json_encode($persons) !!};
        var person = null;

        for (var i = 0; i < persons.length; i++) {
            if (persons[i].id === personId) {
                person = persons[i];
                break;
            }
        }
        debugger;
        document.getElementById('nome-edit').value = person.nome;
        document.getElementById('cpf-edit').value = person.cpf;
        document.getElementById('endereco-edit').value = person.endereco;
        document.getElementById('nascimento-edit').value = person.nascimento;
        document.getElementById('id-edit').value = person.id;
        document.getElementById("modalEdit").action = '{!! url('/').'/' !!}' + 'client/' + person.id;

        var optionElement = document.getElementById('genero-edit');
        for (var i = 0; i < 4; i++) {
            if (optionElement.options[i].value === person.genero) {
                optionElement.options[i].selected = true;
                break;
            }
        }

    }
</script>

resources/views/partials/_dashboardMyModalDelete.blade.php
<div id="myModalDelete" class="modal fade" role="dialog">
    <div class="modal-dialog modal-sm">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Deseja realmente excluir esta pessoa?</h4>
            </div>
            <div class="modal-body">
                <p id="person-id-delete"></p>
                <p id="person-name-delete"></p>
                <p id="person-ssn-delete"></p>
                <p id="person-gender-delete"></p>
                <p id="person-birthday-delete"></p>
                <p id="person-address-delete"></p>

            </div>
            <div class="modal-footer">
                <form id="modalForm" action="{{url('/')}}" method="post">
                    {{method_field('delete')}}
                    {{csrf_field()}}
                    <input type="hidden" id="hrefInputHidden" name="href" value="">
                    <button type="submit" class="btn btn-danger btn-block">
                        Deletar
                    </button>
                </form>


            </div>
        </div>

    </div>
</div>

resources/views/partials/_dashboardMyModalEdit.blade.php
<div id="myModalEdit" class="modal fade" role="dialog">
    <div class="modal-dialog modal-sm">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Editar</h4>
            </div>
            <div class="modal-body">
                <form id="modalEdit" action="" method="POST" role="form">
                    {{method_field('PUT')}}
                    {{csrf_field()}}
                    <input type="hidden" name="id" id="id-edit" value="">

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                <label for="nome-edit">Nome</label>
                                <input name="nome" id="nome-edit" maxlength="191" required class="form-control"
                                       value="">

                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                <label for="cpf-edit">CPF</label>
                                <input name="cpf" type="number" id="cpf-edit" oninput="javascript: if (this.value.length > 11)
                    this.value = this.value.slice(0, 11);" required class="form-control"
                                       value="">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                <label for="genero-edit">Gênero</label>
                                <select class="form-control" required name="genero" id="genero-edit">
                                    <option value="">Selecione
                                    <option value="Feminino">Feminino</option>
                                    <option value="Masculino">Masculino</option>

                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                <label for="endereco-edit">Endereço</label>
                                <input name="endereco" maxlength="191" id="endereco-edit" class="form-control"
                                       value="">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                <label for="nascimento-edit">Nascimento</label>
                                <input name="nascimento" id="nascimento-edit" type="date" required
                                       class="form-control"
                                       value="">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-primary btn-block">Atualizar</button>
                            </div>
                        </div>

                    </div>
                </form>

            </div>
        </div>

    </div>
</div>

resources/views/partials/_dashboardMyModalShow.blade.php
<div id="myModalShow" class="modal fade" role="dialog">
    <div class="modal-dialog modal-sm">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Pessoa</h4>
            </div>
            <div class="modal-body">
                <p id="person-id-show"></p>
                <p id="person-name-show"></p>
                <p id="person-ssn-show"></p>
                <p id="person-gender-show"></p>
                <p id="person-birthday-show"></p>
                <p id="person-address-show"></p>
            </div>
        </div>

    </div>
</div>

resources/views/partials/_dashboardNewPersonForm.blade.php
<form action="{{route('client.store')}}" method="POST" role="form">
    {{method_field('POST')}}
    {{csrf_field()}}
    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                <label for="nome">Nome</label>
                <input name="nome" maxlength="191" required class="form-control">
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                <label for="cpf">CPF</label>
                <input name="cpf" type="number" oninput="javascript: if (this.value.length > 11)
                    this.value = this.value.slice(0, 11);" required class="form-control">
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                <label for="genero">Gênero</label>
                <select class="form-control" required name="genero" id="genero">
                    <option value="">Selection</option>
                    <option value="Feminino">Feminino</option>
                    <option value="Masculino">Masculino</option>
                </select>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                <label for="endereco">Endereço</label>
                <input name="endereco" maxlength="191" class="form-control">
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                <label for="nascimento">Nascimento</label>
                <input name="nascimento" type="date" required class="form-control">
            </div>
        </div>
    </div>


    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary btn-block">Salvar</button>
            </div>
        </div>

    </div>

</form>

resources/views/partials/_dashboardPersonTable.blade.php
<div class="table-responsive">
    <table class="table table-bordered table-hover table-striped">
        <thead>
        <tr>

            <th>Nome</th>
            <th>Cpf</th>
            <th>Genero</th>
            <th>Ações</th>
        </tr>
        </thead>
        <tbody>

        @foreach($persons as $person)
            <tr>

                <td>{{$person->nome}}</td>
                <td>{{$person->cpf}}</td>
                <td>{{$person->genero}}</td>
                <td>
                    <a href="" data-toggle="modal" data-target="#myModalShow"
                       onclick="getPerson({{$person->id}})"><i title="Ver"
                                                               class="fa fa-eye"></i></a>

                    <a href=""
                       data-toggle="modal" data-target="#myModalEdit"
                       onclick="editPerson({{$person->id}})">
                        <i title="Editar"
                           class="fa fa-edit "></i>
                    </a>

                    <a href="" data-toggle="modal" data-target="#myModalDelete"
                       onclick="destroyPerson({{$person->id}})"><i
                                title="Deletar" class="fa fa-trash"></i></a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

resources/views/partials/_headcss.blade.php
<!-- Bootstrap Core CSS -->
<link href="{{asset('startbootstrap-sb-admin-2/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">

<!-- MetisMenu CSS -->
<link href="{{asset('startbootstrap-sb-admin-2/vendor/metisMenu/metisMenu.min.css')}}" rel="stylesheet">

<!-- Custom CSS -->
<link href="{{asset('startbootstrap-sb-admin-2/dist/css/sb-admin-2.css')}}" rel="stylesheet">

{{-- <!-- Morris Charts CSS -->
 <link href="{{asset('startbootstrap-sb-admin-2/vendor/morrisjs/morris.css')}}" rel="stylesheet">--}}

<!-- Custom Fonts -->
<link href="{{asset('startbootstrap-sb-admin-2/vendor/font-awesome/css/font-awesome.min.css')}}"
      rel="stylesheet"
      type="text/css">

resources/views/partials/_navbar.blade.php
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{route('client.index')}}">Neppo</a>
    </div>
    <!-- /.navbar-header -->


    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">

                <li>
                    <a href="{{route('client.index')}}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                </li>


            </ul>
        </div>

    </div>
    <div class="text-center">
        <a href="https://bitbucket.org/cacpmw/frontend-web-based/src/master/" target="_blank"
           class="btn btn-social-icon btn-bitbucket"><i class="fa fa-bitbucket"></i></a>

        <a href="https://www.facebook.com/profile.php?id=100005799405515" target="_blank"
           class="btn btn-social-icon btn-facebook"><i class="fa fa-facebook"></i></a>

        <a href="https://github.com/cacpmw" target="_blank" class="btn btn-social-icon btn-github"><i class="fa fa-github"></i></a>

        <a href="https://www.instagram.com/cacpmw/" target="_blank" class="btn btn-social-icon btn-instagram"><i class="fa fa-instagram"></i></a>
        <a href="https://www.linkedin.com/in/carlos-albuquerque-carneiro-5220398a/" target="_blank" class="btn btn-social-icon btn-linkedin"><i class="fa fa-linkedin"></i></a>


    </div>
</nav>